env = Environment()

env['APP_TARGET'] = 'ColorPickerApp'
env['APP_SOURCES'] = ['ColorPickerApp.cpp']

env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')

