import os

Import('env')

_INCLUDES = [Dir('../include').abspath, Dir('../lib/serial/include').abspath]

_SOURCES = ['SerialDevice.cpp']
_SOURCES = [File('../src/' + s).abspath for s in _SOURCES]

_SERIAL_SOURCES = ['serial.cc', 'impl/unix.cc']
if env['PLATFORM'] == 'darwin':
    _SERIAL_SOURCES += ['impl/list_ports/list_ports_osx.cc']
_SERIAL_SOURCES = [File('../lib/serial/src/' + s).abspath for s in _SERIAL_SOURCES]

env.Append(APP_SOURCES = _SOURCES + _SERIAL_SOURCES)
env.Append(CPPPATH = _INCLUDES)

Return('env')
